### ISSUE TITLE
Add arbitrator actor

### ISSUE THREAD

**Issue by d-plaindoux** [agtors/agar.core#19]
- [x] Handle the NewGameTurn(Player*AOI) message
- [x] Send a tick(AIO) to the related player
- [x] Trigger a TimeOutTurn message
- [x] Handle Move(P*Position) message
- [x] Send Move(P*Position) message to the Region
- [x] Send Move(P*Position) message to the Bridge 
- [x] Handle TimeOutTurn message
- [x] Destroy running player when timeout is reached
- [x] Send DestroyPlayer message for each destroyed player  to the Region

**Comment by NotBad4U** [comment]
We catch the message the message `Consume` and `Move(P*Position)` but how we manage when a player is eaten by another one ? I can send a message between each player like what you did for `Energy` but how we prevent the `Region | Arbitrator` that this player is gone.

**Comment by d-plaindoux** [comment]
The consume should be done once each player has moved and not during the game turn

**Comment by NotBad4U** [comment]
Updated with the merge of #31 the last item is done now
