### ISSUE TITLE
Add journal actor

### ISSUE THREAD

**Issue by d-plaindoux** [agtors/agar.core#20]
- [x] Handle the last Set(Player*AOI) message from the region 
- [x] Unicast the last Set(Player*AOI) message to the client #8 
- [x] Rename to "journal" the current "logger" `class`
- [x] log to stdout for the demo

**Comment by NotBad4U** [comment]
I don't know why but the name "Logger" is not good in my POV. Could we rename this `Journal` like the journal system in a DB or virtual file system (VFS) ?

**Comment by d-plaindoux** [comment]
Logger is not appropriate and semantically poor

**Comment by NotBad4U** [comment]
I'll use websocket instead of `UDP` to make the demo more portable. You can only use UDP in google chrome with an extension and they provide only a `client` socket.

**Comment by NotBad4U** [comment]
Maybe we should persist his state with [Akka Persistence: Event sourcing](https://doc.akka.io/docs/akka/2.5.4/scala/persistence.html)

**Comment by NotBad4U** [comment]
updated with the merge of #29
