### ISSUE TITLE
Create a package "gameplay"

### ISSUE THREAD

**Issue by NotBad4U** [agtors/agar.core#25]
We start to see some package related to the gameplay of the game eg.: Behavior, Player, Energy and  other for the engine: Logger, Arbitrator, ... What do you think @d-plaindoux  about moving everything about the game in a `scala.come.agar.core.gameplay | game` root package ?

**Comment by d-plaindoux** [comment]
It's fine for me.

**Comment by NotBad4U** [comment]
Done in #72f07fa. You should rebase all your branch if you have one.
