### ISSUE TITLE
Detect that a player is now in a new region of the game

### ISSUE THREAD

**Issue by NotBad4U** [agtors/agar.core#5]
We have to detect when a player move in a other region (zone in a game) because we have to move this actor in the `Actorsystem` corresponding to this region.

My proposition is to delegate this job to the `RegionActor` #4. When the position information of a player a receive. He'll evaluate if the player is still in this Region and if not he has to prevent another actor that the Player must to be move. So we need a second actor to track this transaction.

**Comment by d-plaindoux** [comment]
Solved and linked to #6
